pipeline {
    agent any

    tools {
        maven 'Maven-3.9.16'
    }

    stages {
        stage('Build & Unit Test') {
            steps {
                echo 'Fase 1: Mengompilasi kode dan menjalankan pengujian otomatis...'
                bat 'mvn clean package'
            }
        }

        stage('Deploy to SIT') {
            when {
                branch 'develop'
            }
            steps {
                echo 'Fase 2 (SIT): Cabang develop terdeteksi. Mengirim artefak ke server System Integration Testing...'
                // Simulasi perintah pengiriman ke server SIT
                bat 'echo Deploying to SIT Environment...'
            }
        }

        stage('Approval for Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Menunggu otorisasi rilis...'
                input message: 'Validasi artefak siap? Setujui deployment ke server Production?', ok: 'Deploy Sekarang'
            }
        }

        stage('Deploy to Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Fase 3 (PROD): Cabang main terdeteksi. Mengirim artefak ke server utama...'
                // Simulasi perintah pengiriman ke server Production
                bat 'echo Deploying to Production Environment...'
            }
        }
    }
    
    post {
        always {
            bat 'mvn clean'
        }
    }
}